### ISSUE TITLE
左側サイドメニュー内のプルダウンができない

### ISSUE THREAD

**Issue by yucho147** [pallahaxi/calender_deriven_development#4]
下の図のように一方のプルダウンしかできない  
<img width="247" alt="スクリーンショット 2021-05-02 21 41 01" src="https://user-images.githubusercontent.com/53713732/116813529-18391800-ab8f-11eb-9904-535d3ec12cbb.png">  
「Opt 100」はプルダウンできるのに対し、「JuMPチュートリアル」はプルダウンできていない

**Comment by Shoface4039** [comment]
プルダウンしたいコンテンツの `_index.md` において、以下のようにオプションを追加または値を変更する。
`bookCollapseSection: true`
